### ISSUE TITLE
Refactor: Authorization Check in deletePlayer Function

### ISSUE THREAD

**Issue by TrippyGaurav** [BackendsByMTT/Betting_Platform_NodeJS#54]
**Required Changes:**

1. **Authorization Check Before Accessing Player Data:**
   - Before accessing or deleting the player data, verify that the player ID exists in the agent’s `players` array if the role is "agent".
   - If the player ID is not in the agent's `players` array, throw a `401 Unauthorized` error.

2. **Correct Player Deletion:**
   - Only delete the player if the authorization check passes.

**Comment by ranasingh562** [comment]
Done
